apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-install
spec:
  steps:
    - name: install
      image: node:14
      command: ["npm"]
      args: ["install"]
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine-tests
spec:
  steps:
    - name: test
      image: node:14
      command: ["npm"]
      args: ["test"]
